#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ghostscript
Version  : 9.26
Release  : 13
URL      : https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs926/ghostscript-9.26.tar.gz
Source0  : https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs926/ghostscript-9.26.tar.gz
Summary  : An interpreter for the PostScript language
Group    : Development/Tools
License  : AGPL-3.0 BSD-2-Clause BSL-1.0 FTL GPL-2.0 IJG Libpng MIT libtiff
Requires: ghostscript-bin = %{version}-%{release}
Requires: ghostscript-data = %{version}-%{release}
Requires: ghostscript-lib = %{version}-%{release}
Requires: ghostscript-license = %{version}-%{release}
Requires: ghostscript-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-scons
BuildRequires : cups-dev
BuildRequires : dbus-dev
BuildRequires : e2fsprogs-dev
BuildRequires : freeglut-dev
BuildRequires : glu-dev
BuildRequires : gnutls-dev
BuildRequires : krb5-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xt)
BuildRequires : pkgconfig(zlib)
BuildRequires : sed
BuildRequires : tiff-dev
BuildRequires : zlib-dev
Patch1: CVE-2019-6116.patch

%description
ZLIB DATA COMPRESSION LIBRARY
zlib 1.2.11 is a general purpose data compression library.  All the code is
thread safe.  The data format used by the zlib library is described by RFCs
(Request for Comments) 1950 to 1952 in the files
http://tools.ietf.org/html/rfc1950 (zlib format), rfc1951 (deflate format) and
rfc1952 (gzip format).

%package bin
Summary: bin components for the ghostscript package.
Group: Binaries
Requires: ghostscript-data = %{version}-%{release}
Requires: ghostscript-license = %{version}-%{release}
Requires: ghostscript-man = %{version}-%{release}

%description bin
bin components for the ghostscript package.


%package data
Summary: data components for the ghostscript package.
Group: Data

%description data
data components for the ghostscript package.


%package dev
Summary: dev components for the ghostscript package.
Group: Development
Requires: ghostscript-lib = %{version}-%{release}
Requires: ghostscript-bin = %{version}-%{release}
Requires: ghostscript-data = %{version}-%{release}
Provides: ghostscript-devel = %{version}-%{release}

%description dev
dev components for the ghostscript package.


%package doc
Summary: doc components for the ghostscript package.
Group: Documentation
Requires: ghostscript-man = %{version}-%{release}

%description doc
doc components for the ghostscript package.


%package lib
Summary: lib components for the ghostscript package.
Group: Libraries
Requires: ghostscript-data = %{version}-%{release}
Requires: ghostscript-license = %{version}-%{release}

%description lib
lib components for the ghostscript package.


%package license
Summary: license components for the ghostscript package.
Group: Default

%description license
license components for the ghostscript package.


%package man
Summary: man components for the ghostscript package.
Group: Default

%description man
man components for the ghostscript package.


%prep
%setup -q -n ghostscript-9.26
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549254876
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static --with-system-libtiff
make  %{?_smp_mflags} all so

%install
export SOURCE_DATE_EPOCH=1549254876
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ghostscript
cp LICENSE %{buildroot}/usr/share/package-licenses/ghostscript/LICENSE
cp contrib/chp2200/COPYING %{buildroot}/usr/share/package-licenses/ghostscript/contrib_chp2200_COPYING
cp contrib/lxm3200-tweaked/LICENSE %{buildroot}/usr/share/package-licenses/ghostscript/contrib_lxm3200-tweaked_LICENSE
cp doc/COPYING %{buildroot}/usr/share/package-licenses/ghostscript/doc_COPYING
cp freetype/docs/GPLv2.TXT %{buildroot}/usr/share/package-licenses/ghostscript/freetype_docs_GPLv2.TXT
cp freetype/docs/LICENSE.TXT %{buildroot}/usr/share/package-licenses/ghostscript/freetype_docs_LICENSE.TXT
cp jbig2dec/COPYING %{buildroot}/usr/share/package-licenses/ghostscript/jbig2dec_COPYING
cp jbig2dec/LICENSE %{buildroot}/usr/share/package-licenses/ghostscript/jbig2dec_LICENSE
cp lcms2mt/COPYING %{buildroot}/usr/share/package-licenses/ghostscript/lcms2mt_COPYING
cp lcms2mt/utils/jpgicc/LICENSE_iccjpeg %{buildroot}/usr/share/package-licenses/ghostscript/lcms2mt_utils_jpgicc_LICENSE_iccjpeg
cp libpng/LICENSE %{buildroot}/usr/share/package-licenses/ghostscript/libpng_LICENSE
cp libpng/contrib/gregbook/COPYING %{buildroot}/usr/share/package-licenses/ghostscript/libpng_contrib_gregbook_COPYING
cp libpng/contrib/gregbook/LICENSE %{buildroot}/usr/share/package-licenses/ghostscript/libpng_contrib_gregbook_LICENSE
cp openjpeg/LICENSE %{buildroot}/usr/share/package-licenses/ghostscript/openjpeg_LICENSE
cp openjpeg/src/bin/wx/OPJViewer/source/license.txt %{buildroot}/usr/share/package-licenses/ghostscript/openjpeg_src_bin_wx_OPJViewer_source_license.txt
cp tiff/COPYRIGHT %{buildroot}/usr/share/package-licenses/ghostscript/tiff_COPYRIGHT
cp zlib/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/ghostscript/zlib_contrib_dotzlib_LICENSE_1_0.txt
%make_install install-so

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dvipdf
/usr/bin/eps2eps
/usr/bin/gs
/usr/bin/gsbj
/usr/bin/gsc
/usr/bin/gsdj
/usr/bin/gsdj500
/usr/bin/gslj
/usr/bin/gslp
/usr/bin/gsnd
/usr/bin/gsx
/usr/bin/lprsetup.sh
/usr/bin/pdf2dsc
/usr/bin/pdf2ps
/usr/bin/pf2afm
/usr/bin/pfbtopfa
/usr/bin/pphs
/usr/bin/printafm
/usr/bin/ps2ascii
/usr/bin/ps2epsi
/usr/bin/ps2pdf
/usr/bin/ps2pdf12
/usr/bin/ps2pdf13
/usr/bin/ps2pdf14
/usr/bin/ps2pdfwr
/usr/bin/ps2ps
/usr/bin/ps2ps2
/usr/bin/unix-lpr.sh

%files data
%defattr(-,root,root,-)
/usr/share/ghostscript/9.26/lib/PDFA_def.ps
/usr/share/ghostscript/9.26/lib/PDFX_def.ps
/usr/share/ghostscript/9.26/lib/PM760p.upp
/usr/share/ghostscript/9.26/lib/PM760pl.upp
/usr/share/ghostscript/9.26/lib/PM820p.upp
/usr/share/ghostscript/9.26/lib/PM820pl.upp
/usr/share/ghostscript/9.26/lib/Stc670p.upp
/usr/share/ghostscript/9.26/lib/Stc670pl.upp
/usr/share/ghostscript/9.26/lib/Stc680p.upp
/usr/share/ghostscript/9.26/lib/Stc680pl.upp
/usr/share/ghostscript/9.26/lib/Stc740p.upp
/usr/share/ghostscript/9.26/lib/Stc740pl.upp
/usr/share/ghostscript/9.26/lib/Stc760p.upp
/usr/share/ghostscript/9.26/lib/Stc760pl.upp
/usr/share/ghostscript/9.26/lib/Stc777p.upp
/usr/share/ghostscript/9.26/lib/Stc777pl.upp
/usr/share/ghostscript/9.26/lib/Stp720p.upp
/usr/share/ghostscript/9.26/lib/Stp720pl.upp
/usr/share/ghostscript/9.26/lib/Stp870p.upp
/usr/share/ghostscript/9.26/lib/Stp870pl.upp
/usr/share/ghostscript/9.26/lib/acctest.ps
/usr/share/ghostscript/9.26/lib/align.ps
/usr/share/ghostscript/9.26/lib/bj8.rpd
/usr/share/ghostscript/9.26/lib/bj8gc12f.upp
/usr/share/ghostscript/9.26/lib/bj8hg12f.upp
/usr/share/ghostscript/9.26/lib/bj8oh06n.upp
/usr/share/ghostscript/9.26/lib/bj8pa06n.upp
/usr/share/ghostscript/9.26/lib/bj8pp12f.upp
/usr/share/ghostscript/9.26/lib/bj8ts06n.upp
/usr/share/ghostscript/9.26/lib/bjc6000a1.upp
/usr/share/ghostscript/9.26/lib/bjc6000b1.upp
/usr/share/ghostscript/9.26/lib/bjc610a0.upp
/usr/share/ghostscript/9.26/lib/bjc610a1.upp
/usr/share/ghostscript/9.26/lib/bjc610a2.upp
/usr/share/ghostscript/9.26/lib/bjc610a3.upp
/usr/share/ghostscript/9.26/lib/bjc610a4.upp
/usr/share/ghostscript/9.26/lib/bjc610a5.upp
/usr/share/ghostscript/9.26/lib/bjc610a6.upp
/usr/share/ghostscript/9.26/lib/bjc610a7.upp
/usr/share/ghostscript/9.26/lib/bjc610a8.upp
/usr/share/ghostscript/9.26/lib/bjc610b1.upp
/usr/share/ghostscript/9.26/lib/bjc610b2.upp
/usr/share/ghostscript/9.26/lib/bjc610b3.upp
/usr/share/ghostscript/9.26/lib/bjc610b4.upp
/usr/share/ghostscript/9.26/lib/bjc610b6.upp
/usr/share/ghostscript/9.26/lib/bjc610b7.upp
/usr/share/ghostscript/9.26/lib/bjc610b8.upp
/usr/share/ghostscript/9.26/lib/caption.ps
/usr/share/ghostscript/9.26/lib/cbjc600.ppd
/usr/share/ghostscript/9.26/lib/cbjc800.ppd
/usr/share/ghostscript/9.26/lib/cdj550.upp
/usr/share/ghostscript/9.26/lib/cdj690.upp
/usr/share/ghostscript/9.26/lib/cdj690ec.upp
/usr/share/ghostscript/9.26/lib/cid2code.ps
/usr/share/ghostscript/9.26/lib/dmp_init.ps
/usr/share/ghostscript/9.26/lib/dmp_site.ps
/usr/share/ghostscript/9.26/lib/dnj750c.upp
/usr/share/ghostscript/9.26/lib/dnj750m.upp
/usr/share/ghostscript/9.26/lib/docie.ps
/usr/share/ghostscript/9.26/lib/escp_24.src
/usr/share/ghostscript/9.26/lib/font2pcl.ps
/usr/share/ghostscript/9.26/lib/ghostpdf.ppd
/usr/share/ghostscript/9.26/lib/gs_ce_e.ps
/usr/share/ghostscript/9.26/lib/gs_il2_e.ps
/usr/share/ghostscript/9.26/lib/gs_kanji.ps
/usr/share/ghostscript/9.26/lib/gs_ksb_e.ps
/usr/share/ghostscript/9.26/lib/gs_l.xbm
/usr/share/ghostscript/9.26/lib/gs_l.xpm
/usr/share/ghostscript/9.26/lib/gs_l_m.xbm
/usr/share/ghostscript/9.26/lib/gs_lgo_e.ps
/usr/share/ghostscript/9.26/lib/gs_lgx_e.ps
/usr/share/ghostscript/9.26/lib/gs_m.xbm
/usr/share/ghostscript/9.26/lib/gs_m.xpm
/usr/share/ghostscript/9.26/lib/gs_m_m.xbm
/usr/share/ghostscript/9.26/lib/gs_s.xbm
/usr/share/ghostscript/9.26/lib/gs_s.xpm
/usr/share/ghostscript/9.26/lib/gs_s_m.xbm
/usr/share/ghostscript/9.26/lib/gs_t.xbm
/usr/share/ghostscript/9.26/lib/gs_t.xpm
/usr/share/ghostscript/9.26/lib/gs_t_m.xbm
/usr/share/ghostscript/9.26/lib/gs_wl1_e.ps
/usr/share/ghostscript/9.26/lib/gs_wl2_e.ps
/usr/share/ghostscript/9.26/lib/gs_wl5_e.ps
/usr/share/ghostscript/9.26/lib/gslp.ps
/usr/share/ghostscript/9.26/lib/gsnup.ps
/usr/share/ghostscript/9.26/lib/ht_ccsto.ps
/usr/share/ghostscript/9.26/lib/image-qa.ps
/usr/share/ghostscript/9.26/lib/jispaper.ps
/usr/share/ghostscript/9.26/lib/landscap.ps
/usr/share/ghostscript/9.26/lib/lines.ps
/usr/share/ghostscript/9.26/lib/mkcidfm.ps
/usr/share/ghostscript/9.26/lib/necp2x.upp
/usr/share/ghostscript/9.26/lib/necp2x6.upp
/usr/share/ghostscript/9.26/lib/pdf2dsc.ps
/usr/share/ghostscript/9.26/lib/pf2afm.ps
/usr/share/ghostscript/9.26/lib/pfbtopfa.ps
/usr/share/ghostscript/9.26/lib/ppath.ps
/usr/share/ghostscript/9.26/lib/pphs.ps
/usr/share/ghostscript/9.26/lib/prfont.ps
/usr/share/ghostscript/9.26/lib/printafm.ps
/usr/share/ghostscript/9.26/lib/ps2ai.ps
/usr/share/ghostscript/9.26/lib/ps2epsi.ps
/usr/share/ghostscript/9.26/lib/ras1.upp
/usr/share/ghostscript/9.26/lib/ras24.upp
/usr/share/ghostscript/9.26/lib/ras3.upp
/usr/share/ghostscript/9.26/lib/ras32.upp
/usr/share/ghostscript/9.26/lib/ras4.upp
/usr/share/ghostscript/9.26/lib/ras8m.upp
/usr/share/ghostscript/9.26/lib/rollconv.ps
/usr/share/ghostscript/9.26/lib/s400a1.upp
/usr/share/ghostscript/9.26/lib/s400b1.upp
/usr/share/ghostscript/9.26/lib/sharp.upp
/usr/share/ghostscript/9.26/lib/sipixa6.upp
/usr/share/ghostscript/9.26/lib/st640ih.upp
/usr/share/ghostscript/9.26/lib/st640ihg.upp
/usr/share/ghostscript/9.26/lib/st640p.upp
/usr/share/ghostscript/9.26/lib/st640pg.upp
/usr/share/ghostscript/9.26/lib/st640pl.upp
/usr/share/ghostscript/9.26/lib/st640plg.upp
/usr/share/ghostscript/9.26/lib/stc.upp
/usr/share/ghostscript/9.26/lib/stc1520h.upp
/usr/share/ghostscript/9.26/lib/stc2.upp
/usr/share/ghostscript/9.26/lib/stc200_h.upp
/usr/share/ghostscript/9.26/lib/stc2_h.upp
/usr/share/ghostscript/9.26/lib/stc2s_h.upp
/usr/share/ghostscript/9.26/lib/stc300.upp
/usr/share/ghostscript/9.26/lib/stc300bl.upp
/usr/share/ghostscript/9.26/lib/stc300bm.upp
/usr/share/ghostscript/9.26/lib/stc500p.upp
/usr/share/ghostscript/9.26/lib/stc500ph.upp
/usr/share/ghostscript/9.26/lib/stc600ih.upp
/usr/share/ghostscript/9.26/lib/stc600p.upp
/usr/share/ghostscript/9.26/lib/stc600pl.upp
/usr/share/ghostscript/9.26/lib/stc640p.upp
/usr/share/ghostscript/9.26/lib/stc740ih.upp
/usr/share/ghostscript/9.26/lib/stc800ih.upp
/usr/share/ghostscript/9.26/lib/stc800p.upp
/usr/share/ghostscript/9.26/lib/stc800pl.upp
/usr/share/ghostscript/9.26/lib/stc_h.upp
/usr/share/ghostscript/9.26/lib/stc_l.upp
/usr/share/ghostscript/9.26/lib/stcany.upp
/usr/share/ghostscript/9.26/lib/stcany_h.upp
/usr/share/ghostscript/9.26/lib/stcinfo.ps
/usr/share/ghostscript/9.26/lib/stcolor.ps
/usr/share/ghostscript/9.26/lib/stocht.ps
/usr/share/ghostscript/9.26/lib/traceimg.ps
/usr/share/ghostscript/9.26/lib/traceop.ps
/usr/share/ghostscript/9.26/lib/uninfo.ps
/usr/share/ghostscript/9.26/lib/viewcmyk.ps
/usr/share/ghostscript/9.26/lib/viewgif.ps
/usr/share/ghostscript/9.26/lib/viewjpeg.ps
/usr/share/ghostscript/9.26/lib/viewmiff.ps
/usr/share/ghostscript/9.26/lib/viewpbm.ps
/usr/share/ghostscript/9.26/lib/viewpcx.ps
/usr/share/ghostscript/9.26/lib/viewps2a.ps
/usr/share/ghostscript/9.26/lib/winmaps.ps
/usr/share/ghostscript/9.26/lib/zeroline.ps

%files dev
%defattr(-,root,root,-)
/usr/include/ghostscript/gdevdsp.h
/usr/include/ghostscript/gserrors.h
/usr/include/ghostscript/iapi.h
/usr/include/ghostscript/ierrors.h
/usr/lib64/libgs.so

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/ghostscript/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgs.so.9
/usr/lib64/libgs.so.9.26

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ghostscript/LICENSE
/usr/share/package-licenses/ghostscript/contrib_chp2200_COPYING
/usr/share/package-licenses/ghostscript/contrib_lxm3200-tweaked_LICENSE
/usr/share/package-licenses/ghostscript/doc_COPYING
/usr/share/package-licenses/ghostscript/freetype_docs_GPLv2.TXT
/usr/share/package-licenses/ghostscript/freetype_docs_LICENSE.TXT
/usr/share/package-licenses/ghostscript/jbig2dec_COPYING
/usr/share/package-licenses/ghostscript/jbig2dec_LICENSE
/usr/share/package-licenses/ghostscript/lcms2mt_COPYING
/usr/share/package-licenses/ghostscript/lcms2mt_utils_jpgicc_LICENSE_iccjpeg
/usr/share/package-licenses/ghostscript/libpng_LICENSE
/usr/share/package-licenses/ghostscript/libpng_contrib_gregbook_COPYING
/usr/share/package-licenses/ghostscript/libpng_contrib_gregbook_LICENSE
/usr/share/package-licenses/ghostscript/openjpeg_LICENSE
/usr/share/package-licenses/ghostscript/openjpeg_src_bin_wx_OPJViewer_source_license.txt
/usr/share/package-licenses/ghostscript/tiff_COPYRIGHT
/usr/share/package-licenses/ghostscript/zlib_contrib_dotzlib_LICENSE_1_0.txt

%files man
%defattr(0644,root,root,0755)
/usr/share/man/de/man1/dvipdf.1
/usr/share/man/de/man1/eps2eps.1
/usr/share/man/de/man1/gsnd.1
/usr/share/man/de/man1/pdf2dsc.1
/usr/share/man/de/man1/pdf2ps.1
/usr/share/man/de/man1/printafm.1
/usr/share/man/de/man1/ps2ascii.1
/usr/share/man/de/man1/ps2pdf.1
/usr/share/man/de/man1/ps2pdf12.1
/usr/share/man/de/man1/ps2pdf13.1
/usr/share/man/de/man1/ps2pdf14.1
/usr/share/man/de/man1/ps2ps.1
/usr/share/man/man1/dvipdf.1
/usr/share/man/man1/eps2eps.1
/usr/share/man/man1/gs.1
/usr/share/man/man1/gsbj.1
/usr/share/man/man1/gsdj.1
/usr/share/man/man1/gsdj500.1
/usr/share/man/man1/gslj.1
/usr/share/man/man1/gslp.1
/usr/share/man/man1/gsnd.1
/usr/share/man/man1/pdf2dsc.1
/usr/share/man/man1/pdf2ps.1
/usr/share/man/man1/pf2afm.1
/usr/share/man/man1/pfbtopfa.1
/usr/share/man/man1/printafm.1
/usr/share/man/man1/ps2ascii.1
/usr/share/man/man1/ps2epsi.1
/usr/share/man/man1/ps2pdf.1
/usr/share/man/man1/ps2pdf12.1
/usr/share/man/man1/ps2pdf13.1
/usr/share/man/man1/ps2pdf14.1
/usr/share/man/man1/ps2pdfwr.1
/usr/share/man/man1/ps2ps.1
